assets/javascripts/initializers/discourse-calendar.js.es6, lib/event_updater.rb
The max description length for Google's description is 8000 characters, but I maxed the excerpt at 1000.
=> FEATURE: Fill description for events in calendar link

assets/javascripts/connectors/discovery-list-container-top/category-calendar.js.es6, assets/javascripts/initializers/discourse-calendar.js.es6, assets/stylesheets/common/discourse-calendar.scss, config/locales/server.en.yml, config/settings.yml
See calendar categories setting  for usage.
=> FEATURE: allows to show a calendar from a post on a category header

assets/javascripts/discourse/widgets/discourse-post-event.js.es6, assets/javascripts/discourse/widgets/more-dropdown.js.es6, config/locales/client.en.yml, plugin.rb, spec/jobs/export_post_event_report_csv_spec.rb
A new option will appear in event menu:
Once clicked user will receive a notification:
The .csv has this content:
=> FEATURE: allows to export event invitees in a .csv file

assets/javascripts/initializers/discourse-post-event-decorator.js.es6, assets/stylesheets/common/discourse-post-event-preview.scss, config/locales/client.en.yml, test/javascripts/acceptance/discourse-post-event/composer-preview-test.js.es6, test/javascripts/acceptance/discourse-post-event/discourse-post-event-helper.js.es6
This commit also introduces client side tests, this plugin only had server side tests before.
=> FEATURE: displays an error in preview for more than one event

app/models/discourse_post_event/event.rb, assets/javascripts/initializers/decorate-topic-title.js.es6, assets/javascripts/initializers/event-relative-date.js.es6, assets/javascripts/lib/event-relative-date.js.es6, assets/stylesheets/common/discourse-post-event-core-ext.scss, config/locales/client.en.yml, db/migrate/20200926144256_add_unique_index_to_topic_event_ends_at_custom_field.rb, plugin.rb, spec/models/discourse_post_event/event_spec.rb
- always auto updated
- correctly compute based on past/current/future event
- displays a green indicator when an event is on going
=> FEATURE: more dynamic event dates in topic titles

jobs/scheduled/create_holiday_events.rb, plugin.rb
Made sure that events/holidays are loaded in order to prevent an edge case where events would not show up.
Also did a tiny bit of refactoring/cleanup in `create_holiday_events.rb`
=> FIX: sort calendar_details for better holidays support

assets/javascripts/lib/discourse-markdown/discourse-calendar.js.es6, assets/javascripts/lib/discourse-markdown/discourse-post-event-block.js.es6
`whiteList` helper is deprecated and should be replaced with `allowList`
=> FIX: use allowList helper

assets/javascripts/lib/discourse-markdown/discourse-calendar.js.es6, assets/javascripts/lib/discourse-markdown/discourse-post-event-block.js.es6
Reverts discourse/discourse-calendar#82
=> Revert "FIX: use allowList helper"

assets/javascripts/initializers/discourse-calendar.js.es6
This was causing errors when I was playing with Ember CLI, so I fixed it but I forgot to push it :)
=> DEV: Remove global Discourse JS reference

config/settings.yml, spec/jobs/scheduled/destroy_past_events_spec.rb
More people seem to want to keep stuff around, less stuff to explain
=> FEATURE: change delete expired post events to default false

plugin.rb
Follow-up to d469260bf99d1d2f29cd32d3904f8c663e102ed0
=> Fix plugin's compatibility with older discourse versions.

config/locales/server.en.yml
@discourse-translator-bot keep_translations_and_approvals
=> Fix English source string

assets/stylesheets/common/discourse-calendar.scss
=> UX: Fix slider appearance

vendor/holidays/definitions/sa.yaml, vendor/holidays/lib/generated_definitions/sa.rb
https://holidayapi.com/holidays/sa/saudi-national-day
=> Add Saudi National Day holiday

assets/javascripts/connectors/after-chat-channel-username/on-holiday-indicator.hbs
Needs https://github.com/discourse/discourse-chat/pull/388
=> FEATURE: uses after-chat-channel-username outlet to display holiday

vendor/holidays/definitions/sg.yaml, vendor/holidays/lib/generated_definitions/sg.rb
See https://publicholidays.sg/2022-dates/
=> FEATURE: Update SG Holidays for 2022.

config/locales/client.en.yml
see https://github.com/discourse/discourse-calendar/blob/e636c8c307023f515e6184553862a2ac6cddf78b/lib/tasks/javascript.rake#L6
=> Remove unused regions from locale file

assets/javascripts/initializers/discourse-calendar.js.es6
They were previously ignored because of…
```js
/* eslint-disable */
// prettier-ignore
```
=> DEV: Fix minor issues in discourse-calendar.js.es6

assets/stylesheets/common/discourse-calendar.scss, assets/stylesheets/desktop/discourse-calendar.scss
=> FIX: The styling regressed in #220

app/models/calendar_event.rb
See https://meta.discourse.org/t/discourse-calendar/97376/325?u=ryantm for the issue report.
=> FIX remove arrow even if there is no whitespace around it

app/models/discourse_post_event/event.rb, assets/javascripts/discourse/controllers/discourse-post-event-invitees.js, assets/stylesheets/common/discourse-calendar.scss, assets/stylesheets/common/upcoming-events-calendar.scss, jobs/regular/discourse_post_event/send_reminder.rb, plugin.rb
Resolving some post-release TODOs
=> DEV: Drop old code

test/javascripts/acceptance/category-events-calendar-test.js
=> DEV: Temporarily disable test

db/post_migrate/20220613073844_unescape_event_name.rb
On large sites, the migration can take up to 4 hours which is not
something we want. This commit adds the following optimisations:
1. Add an index for notifications `WHERE notifcation_type IN (27, 28)`
1. Increase each batch size to 10000, the smaller the batch size the more
times we have to scan the notifications table.
1. Avoid having to start the scan of the notifications table from id 1
and instead start from the first event notification type.
=> FIX: Optimize performance of UnescapeEventName migration on large sites

config/settings.yml, plugin.rb, spec/requests/site_spec.rb
This is a temporary addition, pending a more radical refactoring of the holiday-emoji-flair system.
=> DEV: Add hidden setting which makes holiday status public

vendor/holidays/definitions/id.yaml
Sources:
- https://kemenkopmk.go.id/sites/default/files/pengumuman/2022-04/Perubahan%20SKB%20Libnas%20%26%20Cuti%20Bersama%20tahun%202022.pdf
- https://publicholidays.co.id/2022-dates/
=> FEATURE: Add Indonesia holidays

vendor/holidays/definitions/br.yaml, vendor/holidays/definitions/nz.yaml, vendor/holidays/lib/generated_definitions/nz.rb, vendor/holidays/test/defs/test_defs_br.rb, vendor/holidays/test/defs/test_defs_nz.rb, vendor/holidays/test/defs/test_defs_southamerica.rb
And also fix some tests for br
=> FEATURE: add Matariki holidays for nz

README.md
Add missing steps to the documentation for updating holidays
=> DEV: Enhance holiday updates workflow documentation

vendor/holidays/definitions/au.yaml, vendor/holidays/lib/generated_definitions/au.rb
see: https://www.pm.gov.au/media/commemorating-her-majesty-queen-elizabeth-ii
=> FEATURE: add Aussie national day of morning

spec/jobs/regular/discourse_post_event/bulk_invite_spec.rb
It now supports strict keyword argument matching by default.
=> DEV: Fix mocha deprecations

app/models/discourse_post_event/event.rb, app/serializers/discourse_post_event/event_serializer.rb, assets/javascripts/discourse/templates/modal/discourse-post-event-builder.hbs, assets/javascripts/discourse/widgets/discourse-post-event-status.js, assets/javascripts/discourse/widgets/discourse-post-event.js, assets/javascripts/initializers/discourse-post-event-decorator.js, assets/javascripts/lib/raw-event-helper.js, assets/stylesheets/common/discourse-post-event-builder.scss, config/locales/client.en.yml, db/migrate/20221223210225_add_minimal_option_to_calendar_event.rb, lib/discourse_post_event/event_parser.rb
It allows hiding the Going/Not going buttons and invitees status
=> FEATURE: Add minimal option to events

assets/javascripts/connectors/after-user-name/holiday-flair.js, config/locales/server.en.yml, config/settings.yml, lib/holiday_status.rb, spec/integration/post_spec.rb, spec/jobs/scheduled/update_holiday_usernames_spec.rb
This allows setting a custom emoji for the holiday status and changes the default from :desert_island: to :date:
=> FEATURE: Option to configure the holiday emoji

assets/javascripts/discourse/templates/admin-plugins-calendar.hbs, assets/javascripts/discourse/templates/components/admin-holidays-list.hbs, assets/javascripts/discourse/templates/discourse-post-event-upcoming-events-index.hbs, assets/javascripts/discourse/templates/modal/discourse-post-event-builder.hbs, assets/javascripts/discourse/templates/modal/discourse-post-event-bulk-invite.hbs, assets/javascripts/discourse/templates/modal/discourse-post-event-invite-user-or-group.hbs, assets/javascripts/discourse/templates/modal/discourse-post-event-invitees.hbs, assets/javascripts/templates/connectors/user-custom-preferences/region.hbs, package.json, yarn.lock
=> DEV: Use angle bracket syntax

assets/stylesheets/common/discourse-calendar.scss
These are now CSS custom properties in core
=> DEV: update box-shadow

vendor/holidays/definitions/ar.yaml
https://en.wikipedia.org/wiki/Public_holidays_in_Argentina#:~:text=August%2017
=> Fix 'Paso a la Inmortalidad del General José de San Martín' holiday date

app/models/discourse_post_event/event.rb, assets/javascripts/discourse/controllers/discourse-post-event-builder.js, config/locales/client.en.yml, config/locales/server.en.yml, lib/discourse_post_event/event_validator.rb, lib/discourse_post_event/rrule_generator.rb, spec/integration/recurrence_spec.rb
This allows us to sync up 2 week and 4 week events, monthly goes out of
sync
Also fixes... test suite failing in Australia
=> FEATURE: allow every 4 weeks as an interval

assets/javascripts/discourse/connectors/before-topic-list-body/category-calendar.gjs, assets/javascripts/discourse/connectors/before-topic-list-body/category-calendar.hbs, assets/javascripts/discourse/connectors/before-topic-list-body/category-calendar.js, assets/javascripts/discourse/connectors/discovery-list-container-top/category-calendar.js, assets/javascripts/discourse/connectors/discovery-list-container-top/category-events-calendar.gjs, assets/javascripts/discourse/connectors/discovery-list-container-top/category-events.hbs, config/settings.yml, test/javascripts/acceptance/category-events-calendar-outlet-test.js
Some components were also converted from HBS+JS to GJS files.
=> FEATURE: add a "none" option to avoid showing the category calendar on any outlet

test/javascripts/acceptance/post-event-builder-test.js
https://github.com/discourse/discourse/pull/23967
=> DEV: Update test css selectors for core change

test/javascripts/integration/components/upcoming-events-list-test.gjs
Helps unblock https://github.com/discourse/discourse/pull/24445
=> DEV: pass url when simulating page:changed on test

assets/stylesheets/common/discourse-calendar.scss
=> FEATURE: add holiday flair on timezones view if the user is on holiday

vendor/holidays/definitions/in.yaml
State: Maharashtra
Country: India
Year: 2024
=> Add Mahashivratri holiday to in.yaml

vendor/holidays/definitions/in.yaml
https://www.tn.gov.in/holiday/2024
=> Update Tamil Nadu (in_tn) holidays for 2024

README.md, vendor/holidays/lib/generated_definitions/ar.rb, vendor/holidays/lib/generated_definitions/northamerica.rb, vendor/holidays/lib/generated_definitions/southamerica.rb, vendor/holidays/lib/generated_definitions/us.rb, vendor/holidays/test/defs/test_defs_ar.rb, vendor/holidays/test/defs/test_defs_northamerica.rb, vendor/holidays/test/defs/test_defs_southamerica.rb, vendor/holidays/test/defs/test_defs_us.rb
Followup to 7f4b174aa937f44623d6806259e3322b294d8f4a
Also updates README with proper command to generate holiday definitions
=> Remove Lee-Jackson Day - generated definitions

spec/jobs/export_post_event_report_csv_spec.rb, spec/models/discourse_post_event/user_spec.rb
This is needed for the change in the core PR
https://github.com/discourse/discourse/pull/25602
=> DEV: Add auto group refresh to specs

test/javascripts/acceptance/notifications-test.js
In preparation for https://github.com/discourse/discourse/pull/26467
=> DEV: Update test selectors for glimmer header

assets/javascripts/discourse/components/event-date.gjs, assets/stylesheets/common/discourse-post-event-core-ext.scss
=> DEV: Fix html structure of topic list event indicators

jobs/scheduled/create_holiday_events.rb, spec/jobs/scheduled/create_holiday_events_spec.rb
When a user changes their holiday region in their profile, we will automatically compute upcoming (6 months) holidays for their new regions. If the events are similar between the two regions, we automatically fix the region. But when they're drastically different, we just leaves the old holiday events be...
It's a somewhat rare event but is annoying enough that it warranted a proper fix.
This ensures we removes any "pre-loaded" holiday events that aren't in the regions the users have selected. That way, no more "fanthom" holidays from the previous region.
Internal ref - t/64785
=> FIX: delete future holidays on region change

README.md
Was setting `upcoming-events-list` up for a customer and realized it's a bit of a hidden/unclear interaction.
=> [DEV] Updates README to with clearer information on Right Sidebar Blocks

README.md
=> [FIX] Update README.md

assets/javascripts/discourse/components/discourse-post-event/invitee.gjs, config/settings.yml
Also restores old default participation buttons
=> FIX: missing localization

assets/stylesheets/common/discourse-post-event.scss, assets/stylesheets/mobile/discourse-post-event.scss
Multiple spacing & sizing adjustments to the post events box.
**After**
**Before**
=> UX: Post event tweaks

test/javascripts/integration/components/upcoming-events-list-test.gjs
Updating the Q-Unit tests to best practices while I'm working nearby
=> updates to qunit best practices

.github/workflows/discourse-plugin.yml, spec/system/disable_sort_spec.rb
https://github.com/discourse/discourse/pull/30375
=> DEV: Update specs for core change

assets/javascripts/discourse/components/modal/post-event-builder.hbs
This add PluginOutlet in modal/post-event-builder component.
We need this to override modal with our customs fields which are not all input text.
Thanks !
=> FEATURE: add plugin outlet in modal/post-event-builder

assets/stylesheets/common/discourse-post-event.scss
Small change in what border radius is applied.
=> UX: border-radius fix

spec/system/post_event_spec.rb
When asserting against the database, we have to consider that
asynchronous nature of system test.
=> DEV: Fix flaky test

config/locales/client.en.yml
It was not clear to the user that the until date would be included.
=> UX: better copy
