discourse/discourse-calendar

spec/jobs/update_holiday_usernames_spec.rb
I was curious why this spec was failing on my local machine.
The reason for that was `from_date` of the post which in this spec was `2018-06-05 10:20:00 UTC`
Because I am in Australia timezone, `freeze_time Time.new(2018, 6, 5, 18, 40)` was giving me `2018-06-05 08:40:00 UTC` which was before `from_date`. 
I think that bug was introduced here: https://github.com/discourse/discourse-calendar/commit/b1fe4456d083be89188bcd57d3f4247a971637f5#diff-b1651fed94990b46f84a76daf7330e2dL17
=> FIX: Freezed time used in update_holiday_usernames_spec.rb should be UTC

jobs/scheduled/check_next_regional_holidays.rb, jobs/scheduled/ensure_consistency.rb, jobs/scheduled/ensure_expired_event_destruction.rb, jobs/scheduled/update_holiday_usernames.rb
Zeitwerk is failing when we are searching for Jobs::Onceoff, Jobs::Base and Jobs::Scheduled without going back to the top-level namespace (this is correlated to the fact that we got Onceoff base class and module with the same name). 
I noticed that in plugins we are using sometimes :: and sometimes not and that gives me comfort that this change will not break anything.
Travis error: https://travis-ci.org/discourse/discourse/jobs/585072364
=> FIX: Use top-level namespace for base classes

jobs/scheduled/check_next_regional_holidays.rb, spec/jobs/check_next_regional_holidays_spec.rb
Previously it would only show the 'next' holiday per region, which makes advance planning difficult
=> FEATURE: Display all holidays for the next 6 months

assets/javascripts/initializers/discourse-calendar.js.es6, jobs/scheduled/check_next_regional_holidays.rb, lib/event_updater.rb, plugin.rb, spec/jobs/check_next_regional_holidays_spec.rb, spec/lib/dynamic_calendar_spec.rb, spec/lib/event_updater_spec.rb
- Render all-day events from 6am to 6pm local time, so that they appear more logically for users in other timezones
- Set the `nextDayThreshold` to 6am, so that multi-day events in slightly more easterly timezones display the end date correctly
As an example, imagine @ZogStriP has entered an event from 23rd - 27th December, and Christmas is on the 25th. I am in GMT, and Regis is GMT+1. To me, his events look like this, which is very confusing:
Following this PR, they will look like this:
6am-6pm are not necessarily the working hours of everyone, but I think they are a better approximation than 12am - 12pm.
=> FEATURE: Improve timezone logic for all-day events

jobs/scheduled/ensure_expired_event_destruction.rb, spec/jobs/ensure_expired_event_destruction_spec.rb
* When the post with the event gets auto-trashed after the event has passed
* BUT do not trash posts that are direct replies IF they have their own events
=> FEATURE: Auto-trash direct replies for post with event that is trashed

assets/javascripts/initializers/discourse-calendar.js.es6, assets/javascripts/lib/discourse-markdown/discourse-calendar.js.es6, assets/stylesheets/common/discourse-calendar.scss
Added these options for the markdown block, which utilise fullcalendar's inbuilt timezone functionality:
* `defaultTimezone` - Provide a default timezone to display the calendar dates in. If this is null we fall back to the current user timezone, and if that is null (or the current user is null) we fall back to moment.tz.guess(). This value is validated.
* `tzPicker` - If set to true, show a dropdown list allowing the user to pick the timezone the calendar displays in. The selected value is based on the rules described in tzdefault. If this is not turned on we show the text of the timezone in the header. The options for the picker come from moment.tz.names() and are rendered into the select at runtime, so we are not storing huge amounts of <option> HTML elements in the DB for no real …
=> FEATURE: Add timezone picker and options

assets/javascripts/connectors/user-custom-preferences/user-timezone.js.es6
If calendar is enabled on a site, the user -> preferences -> profile view breaks. This fixes that.
=> FIX: error breaking other users preference profiles

assets/javascripts/initializers/discourse-calendar.js.es6
Events that go from 11:00pm to 12:00am are showing as all-day. This fixes that.
=> FIX: Events ending at 12:00am are not automatically all-day

plugin.rb
Using custom_fields instead of post_custom_fields triggers a query for the custom field on every post in the topic. Change the include_group_timezones to use post_custom_fields instead which queries every post for the topic on topic view load.
=> FIX: Stop include_group_timezones? N1 query

app/models/discourse_post_event/event.rb
```
DEPRECATION WARNING: Class level methods will no longer
inherit scoping from `not_expired` in Rails 6.1.
To continue using the scoped relation, pass it into
the block directly. To instead access the full set of models,
as Rails 6.1 will, use
`DiscoursePostEvent::Event.default_scoped`.
(called from block in <class:Event> at
/home/runner/work/discourse/discourse/plugins/discourse-calendar/app/models/discourse_post_event/event.rb:44)
```
It's not a solution mentioned in the deprecation warning, but it's simpler, shorter, has one level of indentation less, doesn't create extra ActiveRecord objects, and uses a single Time instance.
=> REFACTOR: Fix Rails 6 scope deprecation warning

assets/javascripts/connectors/after-user-name/holiday-flair.js.es6
I was getting this error from calendar
=> FIX: Error when users_on_holiday is undefined

plugin.rb
This ensures that the patch is reloaded automatically during development, and should stop the random `NoMethodError (undefined method `group_timezones' for #<Post>` errors in development
=> DEV: Use plugin API to amend Post class

assets/javascripts/initializers/discourse-calendar.js.es6
https://meta.discourse.org/t/recurring-events-on-a-sundy-aren-t-showing-up/165780
=> FIX: Recurring events didn't show up on Sundays

assets/javascripts/initializers/discourse-group-timezones.js.es6, assets/javascripts/initializers/discourse-post-event-decorator.js.es6
This could fail in specific cases like discourse-styleguide where we don't get a real post.
=> FIX: ensures we have a post

jobs/scheduled/destroy_past_events.rb, spec/jobs/scheduled/destroy_past_events_spec.rb
Standalone events are mostly created for holidays where we create a calendar event not associated to any post of of the topic, before this change, the loop was exited before collecting the ID of the calendar event to be destroyed.
=> FIX: correctly destroys standalone calendar events

jobs/scheduled/create_holiday_events.rb, spec/jobs/scheduled/create_holiday_events_spec.rb
Since we're generating holidays for the next 6 months, there might be some
leftovers whenever a user is deactivated/suspended/silenced.
PERF: only load timezones informations from concerned users.
We only care about the timezones of the users we will be generating holidays for.
DEV: rename `user_ids_and_timezones` to the clear-but-shorter `timezones`
=> FIX: clean up holidays from deactivated/suspended/silenced users

plugin.rb
`find_each` gets the rows in batches, ordered by the primary key, so
ordering clauses are ignored. If it is not OK to fetch them all from
postgres, then it is also not OK to send them all to the client at once.
=> FIX: find_each does not respect ordering clauses

db/post_migrate/20201111005205_move_data_to_event_dates.rb
Don't create event date when original_ends_at doesn't exist.
This mean that event markdown is not correct
It was throwing error: undefined method `<' for nil:NilClass>
=> FIX: check ends_at in migration to event date

db/post_migrate/20201111005205_move_data_to_event_dates.rb
Remove as much as possible of ActiveRecord and ruby code from event data migration.
=> FIX: remove ActiveRecord from event data migration

plugin.rb, spec/jobs/export_post_event_report_csv_spec.rb
The test is failing because of an incorrect order. I added an order by `created_by`.
Also, I needed to split create_invitess because it is using the same date for `created_at`
```ruby
def create_invitees(attrs)
timestamp = Time.now
attrs.map! do |attr|
{
post_id: self.id, created_at: timestamp, updated_at: timestamp
}.merge(attr)
end
self.invitees.insert_all!(attrs)
end
```
=> FIX: randomly failing export CSV spec

assets/javascripts/discourse/controllers/discourse-post-event-invitees.js.es6
We recently merged a Discourse core's PR to replace usages of Ember's debounce and discourseDebounce with a new debounce wrapper. The new wrapper works exactly like Ember's debounce but internally calls "run" when called in test mode.
This PR replaces all usages of other debounce functions with the new wrapper and fallbacks to Ember's debounce for backward-compatibility.
=> DEV: Use the new discourseDebounce function wrapper.

app/models/discourse_post_event/event_date.rb, spec/models/discourse_post_event/event_date_spec.rb
This commit is to fix this error:
`Job exception: undefined method `<=' for nil:NilClass`
That occurs from the finish method in the monitor_events_dates scheduled
job.
```
app/models/discourse_post_event/event_date.rb:49:in `ended?'
jobs/scheduled/monitor_event_dates.rb:35:in `finish'
jobs/scheduled/monitor_event_dates.rb:11:in `block in execute'
```
This method checks to see if the event has finished and if it has it
will mark it as finished in the database. Some events though don't have
an end date and so this job will throw the above error.
Added a spec file for the event_date model to test for this specific
case.
=> FIX: Cannot compare nil with less than or equal to

jobs/regular/discourse_post_event/send_reminder.rb, spec/jobs/regular/discourse_post_event/send_reminder_spec.rb
We should not error in reminder job when a post is already deleted.
In that case, we should simply skip and don't send any notifications.
=> FIX: reminder job is not erroring when a post is deleted

assets/javascripts/discourse/controllers/discourse-post-event-invitees.js.es6
We need to wrap the new debounce function inside a try block to avoid throwing a "module not found" exception.
=> FIX: Use Ember's debounce on stable.

assets/javascripts/discourse/components/csv-uploader.js.es6, assets/javascripts/discourse/templates/components/csv-uploader.hbs, assets/javascripts/discourse/templates/modal/discourse-post-event-bulk-invite.hbs
For now copy previous component into discourse-calendar plugin
=> FIX: csv-uploader has been removed from core

app/models/discourse_post_event/event.rb, spec/models/discourse_post_event/event_spec.rb
When all events are finished (not pending) serializer is not sorting correctly and not taking the lastly updated event_date. That is causing an issue that even though the database is updated correctly, it is not reflected in UI
=> FIX: event serializer start and end date

plugin.rb, spec/serializers/post_serializer_spec.rb
If a user had two holidays in the same day, the calendar would show
only one of them, but the username would be shown twice. This ensures
the calendar shows both holidays and the username only once.
=> FIX: Handle multiple holidays in the same day

plugin.rb, spec/serializers/post_serializer_spec.rb
It used to handle the case when the same user has multiple holidays in
the same day by joining all holiday names in a single string. This was
a problem when another user was in the same region and had the same
holidays, because each holiday name was duplicated.
=> FIX: Show holiday name only once

assets/javascripts/discourse/widgets/event-invitation-notification-item.js.es6, config/locales/client.en.yml
Needed an extra span in there to match core styling (default text color username, blue link), also shortened text of the default event notification to match other core notification formatting
Before:
After:
=> UX: Update event notification text and markup

assets/stylesheets/common/discourse-post-event-builder.scss
This is due to new native picker taking more inline space than pikaday.
=> UX: makes date time range multiline

app/models/calendar_event.rb
`post.local_dates` is coming from the core discourse plugin, which has the following implementation:
```
add_to_class(:post, :local_dates) do
custom_fields[DiscourseLocalDates::POST_CUSTOM_FIELD] || []
end
```
Meaning we should always at least get an array, however, if the core local dates plugin is disabled, `add_to_class` will be called and the method added, however it will return nothing if the plugin is not enabled.
Source location correctly leads to the `add_to_class` block:
```
[9] pry(main)> Post.last.method(:local_dates).source_location
=> ["/discourse/lib/plugin/instance.rb", 260]
```
=> FIX: prevents exception when accessing `post.local_dates`

plugin.rb
All the preloaded custom fields are stored in `TopicView`'s post_custom_fields property. To prevent N+1 we should that instead of the `post.custom_fields` method.
=> FIX: retrieve custom fields from preloaded data to stop N+1 issue.

assets/stylesheets/common/discourse-calendar.scss
This works in Chrome and Safari; Firefox is still broken for some reason, I'll follow up on that in a separate PR 
Before:
After:
=> FIX: slider input needs z-index for Chrome

assets/javascripts/discourse/widgets/discourse-group-timezones-time-traveler.js.es6, assets/stylesheets/common/discourse-calendar.scss
Turns out Firefox doesn't allow psuedo selectors on range inputs (maybe all inputs), so the bar wasn't rendering at all. Adding a wrapper works fine on all browsers. 
Before:
After:
=> FIX: Firefox doesn't allow pseudos on inputs

app/models/discourse_post_event/event.rb, lib/discourse_post_event/event_finder.rb, spec/fabricators/event_fabricator.rb, spec/lib/discourse_post_event/event_finder_spec.rb
Previously, an edited event could be returned in both expired and non-expired event queries.
=> FIX: Expired/non-expired events logic

app/models/discourse_post_event/event.rb, jobs/regular/discourse_post_event/send_reminder.rb, lib/tasks/javascript.rake, plugin.rb, spec/acceptance/recurrence_spec.rb, spec/jobs/regular/discourse_post_event/send_reminder_spec.rb
Delete previous notifications of recurring events before creating a new one.
=> FEATURE: Re-use existing invite and reminders notifications.

assets/javascripts/discourse/components/csv-uploader.js.es6, assets/javascripts/discourse/templates/components/csv-uploader.hbs, assets/javascripts/discourse/templates/modal/discourse-post-event-bulk-invite.hbs, config/locales/client.en.yml
This commit removes usage of the old upload mixin
and direct hooks into jQuery file upload, which we
are removing in core.
https://github.com/discourse/discourse/pull/15361 must
be merged before this.
=> DEV: Use uppy mixins for CSV uploader

plugin.rb
Using procs lets us pass additional arguments to the function without breaking existing ones.
=> DEV: Use Procs instead of lambdas for the consolidation rule.

app/models/calendar_event.rb, assets/javascripts/initializers/discourse-calendar.js.es6, assets/javascripts/lib/discourse-markdown/discourse-calendar.js.es6, db/migrate/20211216124303_add_timezone_to_calendar_events.rb, plugin.rb
Allow calendar to disrespect timezones and always display full day for standalone and group events.
Standalone events are saved in specific timezone: https://github.com/discourse/discourse-calendar/blob/main/app/models/calendar_event.rb#L62
However, we don't store information about timezone. It is essential to have that information to calculate date properly. Therefore, a new column was added.
=> FEATURE: fullDay calendar option

assets/javascripts/initializers/discourse-calendar.js.es6
fullDay event dates should not be converted into UTC. Like "Australia Day" in UTC is incorrectly "day before".
=> FIX: not UTC for fullDay calendar events

assets/stylesheets/desktop/discourse-calendar.scss
When you zoom in on a browser (safari only) it would manipulate the width of the tables causing the browser to read the table as 'overflown' which would trigger the `expand table` option. Ensure that the table keeps a width of 100% to prevent this from happening. No adverse reactions found in testing new change.
=> Prevent table overflow

vendor/holidays/definitions/us.yaml
Since most businesses are closed for Lundi Gras in South Louisiana, I am adding it to the Discourse Calendar plugin for the `us_la` region.
=> DEV: Add Lundi Gras to Louisiana calendar

assets/stylesheets/common/discourse-calendar.scss, assets/stylesheets/desktop/discourse-calendar.scss
…and collided with other elements, e.g. a calendar emoji in chat message menu
=> FIX: `.calendar` selector was too broad

assets/javascripts/initializers/discourse-calendar.js, assets/javascripts/lib/colors.js
It's not ideal, but at least should handle worst cases.
Before / After
=> UX: Make the event text colors more readable

vendor/holidays/lib/generated_definitions/northamerica.rb, vendor/holidays/lib/generated_definitions/us.rb
@jordanvidrine needed to run `rake generate:definitions` in the `vendor/holidays` directory to update the *.rb files with the latest holidays definitions 😉
=> FIX: apply latest holidays definitions

assets/javascripts/initializers/add-holiday-flair.js
Also slightly refactors the code:
- uses decorateCookedElement
- relies on the fact that cancel accepts undefined
- uses optional chaining
=> FEATURE: adds holiday flair to chat

assets/javascripts/discourse/controllers/discourse-post-event-builder.js, assets/javascripts/discourse/templates/modal/discourse-post-event-builder.hbs, assets/javascripts/initializers/add-event-ui-builder.js, assets/javascripts/lib/raw-event-helper.js, assets/stylesheets/common/discourse-post-event-builder.scss, assets/stylesheets/mobile/discourse-post-event-builder.scss, spec/acceptance/post_spec.rb
It's easier to store a date as UTC and the timezone it should be converted to on display. However, we got to be careful we are not doing any conversion on the frontend.
This commit also does minor UX tweaks to timezones.
=> FIX: ensures client is sending UTC to backend

assets/javascripts/initializers/discourse-calendar.js, assets/stylesheets/common/discourse-calendar.scss
The main fix is that of the common holiday events displayed in the mobile list: 
(Event name displayed by defauilt, on click, details of participants are shown in a popover)
This PR also makes some adjustments to the events on desktop (i.e. switching from `d-popover` to `popper`)
The background color change (from secondary to tertiary low) has been made to make it easier to use popper's arrow utility. 
Ideally, this PR should have tests, I'm going to look into that in a followup PR.
=> UX: Adjust calendar event display

app/controllers/discourse_post_event/events_controller.rb, assets/javascripts/initializers/discourse-calendar.js, assets/javascripts/templates/connectors/discovery-list-container-top/category-events.hbs, config/locales/server.en.yml, config/settings.yml, spec/requests/events_controller_spec.rb, test/javascripts/acceptance/category-events-calendar-test.js
This commit adds a new site setting `events calendar category` for events calendar that is separate and independent from `calendar categories`. If a category is present in both `events calendar category` and `calendar categories` then priority is given to `calendar categories`.
=> FEATURE: add events calendar on the category page

assets/javascripts/initializers/discourse-calendar.js, assets/javascripts/templates/connectors/discovery-list-container-top/category-events.hbs, assets/stylesheets/common/upcoming-events-calendar.scss, test/javascripts/acceptance/category-events-calendar-test.js
Previously the ID for standard upcoming events calendar and category
events calendar was same and on every page change we were hiding the
category events calendar. Due to this the upcoming events calendar were
getting hidden when navigating away from page but was not reloading on
visiting again. This commit changes the ID for category events calendar
so that we can have finer control over it.
Internal ticket t61598.
=> FIX: do not hide upcoming events calendar when navigating away from page

assets/javascripts/initializers/discourse-calendar.js
- timezone picker now defaults to user's timezone (and works)
- for more than 2 people (instead of 3), show holiday name
- remove some jQuery
=> UX: Fix timezone picker and multi-person logic

vendor/holidays/definitions/sa.yaml, vendor/holidays/lib/generated_definitions/sa.rb
The 2nd of May to the 4th of May of 2022 is a public holiday in Saudi Arabia as per https://holidayapi.com/countries/sa/2022.
=> Add upcoming Saudi holidays (Eid Al Fitr)

vendor/holidays/definitions/gb.yaml
Changes from upstream `holidays` gem
=> Update UK bank holiday definitions for Platinum Jubilee

plugin.rb, spec/serializers/user_serializer_spec.rb
The 'holidays-region' custom field used to be visible only to staff
members, but editable by the current user. This meant that the user
could edit the value, but could not see the value after it was set.
This caused the input field from their user preferences page to be
always blank for regular users.
=> FIX: Make region visible to current user too

app/controllers/admin/admin_discourse_calendar_controller.rb, app/controllers/admin/discourse_calendar/admin_holiday_regions_controller.rb, app/controllers/admin/discourse_calendar/admin_holidays_controller.rb, config/locales/server.en.yml, plugin.rb, spec/requests/admin/admin_holiday_regions_controller_spec.rb, spec/requests/admin/admin_holidays_controller_spec.rb
This will make two new endpoints available to admins:
* `/admin/discourse-calendar/holiday-regions` - this will return a list of holiday regions (as defined by the Holidays gem)
* `/admin/discourse-calendar/holiday-regions/:id/holidays` - this will return all of the holidays for a given region
The next piece I will work on for this will be a UI update so that admins can select a region and view all of the holidays for that region (and eventually the ability to enable/disable holidays).
I wanted to keep the PRs smaller to make them easier to review, and also to make sure I'm on the right track. Still new to contributing so any feedback is welcome! :smiley:
=> DEV: Add API endpoints for holidays

assets/javascripts/discourse/controllers/discourse-post-event-builder.js, assets/javascripts/discourse/templates/modal/discourse-post-event-builder.hbs, assets/javascripts/initializers/add-event-ui-builder.js, assets/javascripts/lib/raw-event-helper.js, assets/stylesheets/common/discourse-post-event-builder.scss, assets/stylesheets/mobile/discourse-post-event-builder.scss, spec/acceptance/post_spec.rb
This reverts commit 2c827c5a070a910648cb8d2cd9bd5fab55d3144c.
We're reverting the commit because the core components for date/time input that this plugin depends still work with the local timezone of the user rather UTC which causes weird problems due to moment.js objects being in different timezones to what the core components and this plugin expect.
=> Revert "FIX: ensures client is sending UTC to backend (#241)"

vendor/holidays/definitions/us.yaml, vendor/holidays/lib/generated_definitions/northamerica.rb, vendor/holidays/lib/generated_definitions/us.rb
According to https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays#url=2022, Juneteenth should be added to the US holiday list with observance on the closest weekday it falls on a weekend.
=> Add Juneteenth holiday for US

assets/stylesheets/common/discourse-post-event.scss
Just saw a little ui bug: when the name of an event is too long it overflows and the dropdown isn't visible
added css to make ellipsis work:
=> UX: tiny css fix

app/controllers/admin/discourse_calendar/admin_holidays_controller.rb, app/models/discourse_calendar/disabled_holiday.rb, app/models/discourse_post_event/event.rb, app/models/discourse_post_event/invitee.rb, app/services/discourse_calendar/holiday.rb, assets/javascripts/discourse/components/admin-holidays-list-item.js, assets/javascripts/discourse/templates/admin-plugins-calendar.hbs, assets/javascripts/discourse/templates/components/admin-holidays-list-item.hbs, assets/javascripts/discourse/templates/components/admin-holidays-list.hbs, assets/stylesheets/common/discourse-calendar-holidays.scss, config/locales/client.en.yml, config/locales/server.en.yml, db/migrate/20220604200919_create_disabled_holidays.rb, jobs/scheduled/create_holiday_events.rb, plugin.rb, spec/jobs/scheduled/create_holiday_events_spec.rb, spec/requests/admin/admin_holidays_controller_spec.rb, spec/services/discouse-calendar/holiday_spec.rb, test/javascripts/acceptance/admin-holidays-test.js, test/javascripts/integration/components/admin-holidays-list-item-test.js
The functionality in this PR will allow admins to enable and disable holidays.
Some notes about disabled holidays:
- They won't get added to the calendar
- For holidays already on the calendar, they will get removed when they are disabled
An overview of the changes in this PR:
- Disabled holidays will get saved in a new `disabled_holidays` table
- A new `Holiday` service was added that will find holidays (from the Holidays gem) and attach a `disabled` field
- Two backend endpoints were added to disable and enable holidays
- A new `admin-holidays-list-item` component was added that will display an individual holiday and a disable or enable button, this component also includes the AJAX calls to hit the new corresponding backend endpoints
All feedback welcome! :+1: :smiley:
=> Allow admins to enable and disable holidays

app/models/discourse_post_event/event.rb, assets/javascripts/discourse/controllers/discourse-post-event-builder.js, assets/javascripts/discourse/templates/modal/discourse-post-event-builder.hbs, assets/javascripts/initializers/add-event-ui-builder.js, assets/javascripts/initializers/discourse-post-event-decorator.js, assets/javascripts/lib/raw-event-helper.js, config/locales/server.en.yml, db/migrate/20220724130519_fix_post_event_timezones.rb, spec/acceptance/post_spec.rb, spec/acceptance/recurrence_spec.rb, test/javascripts/acceptance/post-event-builder-test.js
Previously we were storing a 'UTC' datetime in the database which was in fact a local datetime. That means that, every time it was accessed, consumers would have to ignore the "Z" suffix and parse it using the specified `timezone`.
Adding that kind of logic to every consumer would be very error-prone. Instead, this commit changes the implementation so that `original_start_time` and `original_end_time` are 'technically correct', truly-UTC timestamps. Consumers that need to obtain the original 'local' timestamp (e.g. recurrence) can do something like `original_start_time.in_timezone(timezone)`. Most consumers (e.g. notifications, event-countdown UI, etc.) don't care about the original timezone, and so they can now stick to using `original_start_time` without issue.
A number of specs are …
=> FIX: Handle non-UTC events correctly

assets/javascripts/discourse/controllers/discourse-post-event-builder.js
This happens when editing an existing event via the `[...]` button
=> FIX: Ensure timezone change works even when timestamp is a string

plugin.rb, spec/models/discourse_post_event/user_spec.rb
If someone has edit access on a post (e.g. they're TL4), then it makes sense for them to be able to edit the attached event
=> FEATURE: Allow post events to be edited based on post guardian

assets/javascripts/initializers/add-holiday-flair.js, assets/stylesheets/common/discourse-calendar.scss, test/javascripts/acceptance/holiday-flair-test.js
In some places like mention and assign, we displayed calendar-alt for holiday. It should be consistent, and we should display tropical island everywhere.
Before:
After
=> FIX: consistent desert island icon for holidays

assets/javascripts/discourse/controllers/discourse-post-event-builder.js, assets/javascripts/discourse/templates/modal/discourse-post-event-builder.hbs
Requires https://github.com/discourse/discourse/pull/17654 to function, but will be a safe no-op without so we don't need a `.discourse-compatibility` change
=> FIX: Ensure date/time pickers behave correctly in all timezones

assets/javascripts/initializers/add-event-ui-builder.js, assets/javascripts/initializers/add-hamburger-menu-action.js, assets/javascripts/initializers/add-holiday-flair.js, assets/javascripts/initializers/decorate-topic-title.js, assets/javascripts/initializers/discourse-calendar.js, assets/javascripts/initializers/discourse-group-timezones.js, assets/javascripts/initializers/discourse-post-event-decorator.js
**Update** the following services references:
- `site-settings:main` ->  `service:site-settings`
- `site-main` -> `service:site`
to remove the following deprecation warnings:
```bash
[PLUGIN discourse-calendar] Deprecation notice: "site-settings:main" is deprecated, use "service:site-settings" instead (deprecated since Discourse 2.9.0.beta7) (removal in Discourse 3.0.0)
[PLUGIN discourse-calendar] Deprecation notice: "site:main" is deprecated, use "service:site" instead (deprecated since Discourse 2.9.0.beta7) (removal in Discourse 3.0.0)
```
=> DEV: Update service references

config/locales/client.en.yml
Ensure new Ghana holiday region is properly translated and displayed in UI
=> FIX: Update regions translation to include Ghana

assets/javascripts/discourse/widgets/event-invitation-notification-item.js, assets/javascripts/discourse/widgets/event-reminder-notification-item.js, assets/javascripts/initializers/discourse-calendar.js, config/locales/client.en.yml, test/javascripts/acceptance/notifications-test.js
This PR ports the widgets-based implementation of the `event_reminder` and `event_invitation` notification items to the experimental Glimmer-based user menu. The changes in this PR should make event notifications in the experimental user menu consistent with they look/behave in the old user menu.
We don't need to add a `.discourse-compatibility` entry for this change because it's fully backward compatible since we check that the `registerNotificationTypeRenderer` plugin API is available before we attempt to use it.
For more context on the experimental user menu, see https://github.com/discourse/discourse/pull/17379.
=> DEV: Add support for the experimental user menu

vendor/holidays/definitions/gb.yaml, vendor/holidays/lib/generated_definitions/europe.rb, vendor/holidays/lib/generated_definitions/gb.rb, vendor/holidays/test/defs/test_defs_europe.rb, vendor/holidays/test/defs/test_defs_gb.rb
https://www.gov.uk/bank-holidays
The only human-made change is to `gb.yaml`. The other changes were created by `rake generate:definitions`
=> Add GB holiday definition for Queen's State Funeral (2022-09-19)

config/locales/client.en.yml
The missing entry caused an untranslated string to be present in the region dropdown.
=> FIX: Add translation entry for Indonesia

plugin.rb
This was causing an error on topic lists after a zeitwerk reload. Using the official plugin API takes care of reloading correctly.
=> DEV: Ensure topic_list custom field preloading persists in development

assets/javascripts/initializers/disable-sort.js
This PR suppresses the console warning:
```
[PLUGIN discourse-calendar] To prevent errors in tests, add a `pluginId` key to your `modifyClass` call. This will ensure the modification is only applied once.
```
by adding the `pluginId` attribute to the topic-list component class modification.
=> DEV: Add `pluginId` to suppress console warning

plugin.rb
This was causing an error on topic lists after a zeitwerk reload. Using the official plugin API takes care of reloading correctly.
Followup to 139fdd9cc3a637eca16481220ac032a49952d0ab
=> DEV: Ensure ends_at preloading persists in development

spec/lib/discourse_post_event/event_finder_spec.rb
See https://github.com/discourse/discourse/pull/18437, we are removing any references to enable_personal_messages in core and using only personal_message_enabled_groups, which requires auto groups to be assigned in certain specs for them to keep working.
=> DEV: Fix specs for personal_message_enabled_groups setting

test/javascripts/acceptance/post-event-builder-test.js
In preparation for core PR https://github.com/discourse/discourse/pull/18413
which changes JS to load default yml site settings,
the main one needing changes is that now the
allow_uncategorized_topics setting is false
by default, so we have to choose a category
first in many places.
=> DEV: Fix JS tests to handle default site settings

assets/javascripts/initializers/disable-sort.js, test/javascripts/acceptance/sort-event-topics-test.js
- Disabling of header sorting now checks the correct site setting and defaults to false
- Corresponding qunit test fixed to set the category's disable_topic_resorting custom_field before running the test
=> FIX: Disabling of header sorting now checks the correct site setting and defaults to false

jobs/scheduled/update_holiday_usernames.rb, spec/jobs/scheduled/update_holiday_usernames_spec.rb
Starting from ccb4993e5700b0f090999ad3c636111015b2a7d4 the calendar plugin sets user status in Core when user is on holiday. But in case a user already set a status by themselves, the calendar plugin doesn't overwrite that status.
Sometimes users set status with the removing timer. After such a status expired, it disappears everywhere, but still there is a row in the table in the database (when ends_at is in the past backend doesn't send such status to the client). The calendar plugin was seeing such expired rows in the user_statuses table, and hence wasn't setting a holiday status.
Since effectively an expired status doesn't exist, the calendar plugin should be overwriting such status when a user is on holiday.
=> FIX: calendar wasn't resetting expired statuses

config/settings.yml, plugin.rb, spec/requests/site_spec.rb
It was a temporary addition, see 67b81b3d691437089aefb00d01995ecc5973780a. After ccb4993e5700b0f090999ad3c636111015b2a7d4 it doesn't take any effect.
=> DEV: Drop hidden setting which was making holiday status public

plugin.rb
Due to the security fix ca5ae3e7e0c2b32af5ca4ec69c95e95b2ecef2e9
=> SECURITY: Bump the version

app/models/calendar_event.rb, jobs/scheduled/update_holiday_usernames.rb, lib/holiday_status.rb, spec/integration/post_spec.rb, spec/jobs/scheduled/update_holiday_usernames_spec.rb
Before this PR, it took up to 10 minutes for status to update after posting on the calendar topic or editing an existing calendar topic post. Now status will be updating immediately.
=> FEATURE: set holiday status immediately when adding or updating calendar post

app/models/discourse_post_event/event_date.rb, spec/jobs/scheduled/monitor_event_dates_spec.rb
When the post is deleted, the linked event is automatically deleted as well. 
Job should not try to process deleted events.
=> FIX: exclude deleted events from MonitorEventJob

plugin.rb
These overrides are not using the DiscoursePluginRegistry, and therefore need to be re-applied after a Zeitwerk reload to prevent errors
=> DEV: Fix Zeitwerk reloading in development

app/models/calendar_event.rb, lib/users_on_holiday.rb, spec/lib/users_on_holiday_spec.rb
If a user has several holidays one after another, we want to show the farthest end date.
For example, let's say today is Monday, and I am sick, and I also have days off from Tuesday to Friday. Then we want to show Friday as an end date of my time off.
Or let's say I have a vacation from Monday to Friday and at the same time there is a public holiday in my country on Monday. We want to show Friday as the end of my time off in this case.
=> FEATURE: handle subsequent and intersected holidays

lib/discourse_post_event/event_validator.rb, spec/integration/post_spec.rb
Context: https://meta.discourse.org/t/event-calendar-plugin-official-broken-publik-events/246731
=> FIX: handle localised automatic group names in event validation

spec/requests/admin/admin_holidays_controller_spec.rb
The spec checks specific 2022 holidays, so it started to fail as soon as we entered 2023. 😉 Freezing the time to 2022 fixes the problem.
=> DEV: Fix a spec tied to a specific year

plugin.rb, spec/integration/curently_away_report_spec.rb
Return an empty array instead of nil when the plugin store has not yet been populated with `users_on_holiday`.
At the moment, the `currently_away` report fails if the `UpdateHolidayUsernames` never gets the chance to update `users_on_holiday`.
=> FIX: Make users_on_holiday return type consistent

config/locales/server.en.yml
Event reminder push notification title was not translated. This change adds it.
=> FIX: Add missing translation for event reminder push notification title

plugin.rb
Currently, the `update_from_raw` function gets called by the `:post_process_cooked` event,. This sometimes causes the event not to load after creating it. I haven't been able to pinpoint the exact problem here, but my best bet is that it's some sort of timing-related issue, as it's fairly inconsistent to reproduce.
Since `update_from_raw` doesn't affect the cooked output, triggering it earlier solves the loading problem.
=> FIX: Sometimes the event doesn't load after creating it

config/locales/server.en.yml, config/settings.yml, jobs/scheduled/create_holiday_events.rb, spec/jobs/scheduled/create_holiday_events_spec.rb
Automatic holidays can not be disabled by disabling
`calendar_automatic_holidays_enabled`
By default we will set automatic holidays
=> FEATURE: allow disabling automatic holidays globally

vendor/holidays/definitions/sg.yaml
Updating 2023 holidays for Singapore since some are due to lunar, hindu, or islamic calendars. Changes:
| Date | Day | Event | Note
| -- | -- | -- | -- |
22, 23 January 2023 | Sunday Monday |  Chinese New Year | Tuesday, 24 January 2023, will be a public holiday.
7 April 2023 | Friday | Good Friday
22 April 2023 | Saturday | Hari Raya Puasa | Observed on the following Monday 24th April 2023.
2 June 2023 | Friday |   Vesak Day
29 June 2023 | Thursday   | Hari Raya Haji
12 November 2023 | Sunday |   Deepavali | Monday, 13 November 2023, will be a public holiday.
=> FIX: Update CNY for Singapore

app/serializers/discourse_post_event/event_serializer.rb, jobs/scheduled/monitor_event_dates.rb, spec/jobs/scheduled/monitor_event_dates_spec.rb
The migration did not change the raw topic content. Therefore, if you edit and save the event through the composer (not the modal), it applied back the old format. This change is to deal with those cases.
old syntax:   `reminders="<value>.<unit>"`
new syntax:  `reminders="<type>.<value>.<unit>"`
=> FIX: Add backward compatibility for reminders

app/models/discourse_post_event/event.rb, spec/integration/post_spec.rb, spec/integration/recurrence_spec.rb
Invitation notifications for events are sent to all those who participate in them whenever the event dates are modified. While this is useful for keeping everyone on track with the latest changes, it may not be necessary for recurring events where the next scheduled date is already known.
This PR disables notifications in such situations. Note that the reminders will still be sent if changes are made manually, and configurable reminders will remain the same.
=> FIX: Disable invitation notifications for recurrent events

vendor/holidays/lib/generated_definitions/ca.rb, vendor/holidays/lib/generated_definitions/northamerica.rb
Update config so that Saint Jean Baptiste, on June 26 is observed on Monday (June 26), since it falls on a weekend this year.
=> FIX: Quebec's national holiday observed Monday

lib/tasks/javascript.rake
The consts in javascript.rake were not assigned with ||=
so we would end up with tons of errors like this when running
specs for this plugin:
> warning: already initialized constant TIMEZONES_DEFINITIONS
> warning: previous definition of TIMEZONES_DEFINITIONS was here
=> DEV: Fix const redefine warnings in javascript.rake

vendor/holidays/definitions/gh.yaml, vendor/holidays/lib/generated_definitions/gh.rb, vendor/holidays/test/defs/test_defs_gh.rb
See: https://www.mint.gov.gh/declaration-of-wednesday-28th-june-2023-as-a-statutory-public-holiday/
=> DEV: Add Eid-ul-Adha Holiday for Ghana

spec/models/discourse_post_event/user_spec.rb
Same issue outlined in this PR - https://github.com/discourse/discourse-staff-alias/pull/53
Core change relies on user's group_ids and they need to be refreshed for spec to pass.
=> DEV: Refresh auto groups in user_spec

app/controllers/discourse_post_event/events_controller.rb, app/models/discourse_post_event/event.rb, spec/models/discourse_post_event/event_spec.rb
**Context**
The calendar plugin allows the creation of events, and the notification of users of the existence of that event after it has been created
**Problem**
When trying to notify a user the notification never shows on the user's side. The methods involved in the notification seem to be missing information
**Solution**
Fix the methods involved in the notification flow
=> FIX: Missing event user notifications

assets/javascripts/connectors/before-topic-list-body/category-calendar.js, assets/javascripts/connectors/discovery-list-container-top/category-calendar.js
The `calendar categories` feature was broken because `ctx.name` returns `undefined` (I believe due to the way arguments are passed in to plugin outlets after core updates?).
Hardcoding the name here works.
=> FIX: add outlet names, they're no longer passed in

assets/javascripts/discourse/initializers/discourse-calendar.js, assets/stylesheets/common/discourse-calendar.scss, config/locales/server.en.yml, config/settings.yml, plugin.rb, spec/serializers/post_serializer_spec.rb, test/javascripts/acceptance/timezone-offset-test.js
This PR adds the option to enable a timezone adjustment for calendar events. This will make it so events render offset from the grid to reflect the appropriate start and end moments according to the viewer's timezone.
- Events will rerender when changing the timezone from the timezone picker
- The calendar needs to be full day (`fullDay="true"`)
- The hidden site setting is `enable_timezone_offset_for_calendar_events`
<div align="center"> <h3>Denver (GMT-6) / Tokyo (GMT+9)</h3>
</div>
By default, grouped events (holidays) get split by timezone. This can be configured. If the timezone difference between events is less than a set threshold, events get grouped anyway and will be displayed with the timezone closest to the average.
- The hidden site setting is …
=> FEATURE: Display calendar events adjusted for timezones

assets/javascripts/discourse/initializers/discourse-calendar.js, assets/stylesheets/common/discourse-calendar.scss, config/locales/client.en.yml, config/settings.yml, test/javascripts/acceptance/timezone-offset-test.js
- The button only appears when `enable_timezone_offset_for_calendar_events` is set to true.
- The option is not persistent; it resets each time the calendar is loaded.
- By default, the offset is disabled and is configurable via `default_timezone_offset_user_option`.
- Similar to changing the timezone, it takes some time to rerender the events, depending on the number of them.
=> FEATURE: Add user option to toggle timezone adjustment

test/javascripts/acceptance/sidebar-upcoming-events-item-test.js
Why this change?
The legacy navigation menu has been deprecated for quite awhile and will
soon be removed.
What does this change do?
Update the tests to test against the `sidebar` navigation menu instead
which is the default for a new Discourse install.
=> DEV: Update QUnit acceptance test to not rely on legacy nav menu

assets/javascripts/discourse/initializers/discourse-calendar.js, test/javascripts/acceptance/timezone-offset-test.js, test/javascripts/acceptance/topic-calendar-events-test.js
`new Date("2023-10-12 07:00:00-03:00")` -> `Date Thu Oct 12 2023 07:00:00 GMT-0300`
`new Date("2023-10-12 07:00:00 -03:00")` -> `Invalid Date`
=> FIX: Calendar events not rendering in Firefox

test/javascripts/acceptance/topic-calendar-events-test.js
The cause of the flakiness seems to be buried deep in Discourse core, and we're not exactly sure why this particular test has awoken the problem. Skipping for now while we dig into the problem.
=> DEV: Skip flaky test

test/javascripts/acceptance/topic-calendar-events-test.js
This reverts commit 8aba8c323194075369e916cd9a32acd2da96c6a5.
The flakiness should be resolved by https://github.com/discourse/discourse/commit/597ef1119536693ef0bc7fe799ff485047f9f6f7
=> Revert "DEV: Skip flaky test (#453)"

app/serializers/discourse_post_event/event_serializer.rb, assets/javascripts/discourse/components/upcoming-events-calendar.js, assets/javascripts/discourse/initializers/discourse-calendar.js, assets/stylesheets/common/upcoming-events-calendar.scss, spec/serializers/discourse_post_event/event_serializer_spec.rb, test/javascripts/acceptance/upcoming-events-calendar-test.js
We've hardcoded the events to `var(--tertiary)`. Many users have requested that events be the colour of their categories.
I attempted to add an acceptance test to assert that the colours match the category colours defined in the fixtures, but 
```
query(".fc-event-container").style.backgroundColor
```
returns `'rgb(37, 170, 226)'` value which is slightly annoying to assert against...
Category calendar now:
Upcoming calendar now:
=> FEATURE: Use event category's color for calendar event

assets/javascripts/discourse/initializers/discourse-calendar.js, config/locales/client.en.yml, test/javascripts/acceptance/category-events-calendar-test.js
Passes the current locale (converted to BCP 47) to the FullCalendar initialization, in addition to a custom `buttonText` object from our I18n.
There's a ["locales"](https://fullcalendar.io/docs/locale) file that could be used from FullCalendar, but it's 20kb minified, I don't think it's worth it.
=> UX: pass the current locale to FullCalendar

assets/javascripts/discourse/components/upcoming-events-calendar.js, assets/stylesheets/common/upcoming-events-calendar.scss
Fallback to a default color if there's no category_id.
A user may manually copy the event from a topic or convert one to a PM, leaving the event without a category.
=> FIX: fallback category color if there's no category

spec/integration/invitee_spec.rb, spec/integration/topic_spec.rb, spec/requests/invitees_controller_spec.rb
The `#queue_jobs=` method on site settings has been [deprecated](https://github.com/discourse/discourse/commit/1b65469b64e9e569fed67ae11f1dd9ee37702f5c) and replaced by `Jobs.run_later!` and `Jobs.run_immediately!`. This PR replaces usages in this plugin so we can remove the fallback in core.
The fallback used in core for reference:
https://github.com/discourse/discourse/blob/main/app/models/site_setting.rb#L109-L115
=> DEV: Replace deprecated queue_jobs site setting in tests

config/locales/server.en.yml
As the `sidebar show upcoming events` setting was previously grouped within the Calendar settings group a note to ensure 'post event' was enabled was added. Once grouped with the Event settings, this became superfluous.
=> FIX: Remove note from `sidebar show upcoming events` description

config/settings.yml
Currently the `sidebar_show_upcoming_events` is displaying in the Calendar group and not the Event group. This commit moves it into the correct group
=> FIX: Move `sidebar_show_upcoming_events` into Event settings

config/locales/server.en.yml
Removes 'experimental' from the `discourse_post_event_enabled` plugin setting
=> UX: Remove 'experimental' from discourse_post_event_enabled

lib/discourse_post_event/event_parser.rb, spec/lib/discourse_post_event/event_parser_spec.rb
Event URLs are used on `a` `href`s and shouldn't be HTML-escaped.
=> FIX: skip html escaping event urls

app/controllers/discourse_post_event/events_controller.rb, assets/javascripts/discourse/initializers/discourse-calendar.js, spec/requests/events_controller_spec.rb
Currently on any category page e.g. /c/general/1, sub category events are not shown on the parent calendar. This fix shows sub categories on the parent category's calendar.
=> FIX: Show sub category events

assets/javascripts/discourse/initializers/discourse-calendar.js, jobs/scheduled/create_holiday_events.rb, plugin.rb, test/javascripts/acceptance/topic-calendar-holidays-test.js
When a public holiday is created, it is created in a specific user time zone.
https://github.com/discourse/discourse-calendar/blob/main/jobs/scheduled/create_holiday_events.rb#L71
When calendar is set as fullDay, we would like to display Christmas always 25th of December.
To achieve that, we need to have information about timezone, parse date in that timezone, and leave only year, month and day.
I added a test case to cover one bug scenario. User from Los Angeles have seen that user from Italy was celebrating Christmas Day on 24th of December instead of 25th.
=> FIX: regional public holidays day early

db/migrate/20231123233308_delete_duplicated_holidays.rb, jobs/scheduled/create_holiday_events.rb, spec/jobs/scheduled/create_holiday_events_spec.rb
When username was changed, the scheduled job was creating duplicated holidays.
In addition to fix, migration was added to remove duplicated and incorrect records.
=> FIX: prevent holiday duplicates when username is changed

db/migrate/20231124021939_delete_similar_holidays.rb, jobs/scheduled/create_holiday_events.rb, spec/jobs/scheduled/create_holiday_events_spec.rb
When a user updates timezone, it creates duplicated holidays.
Beside the fix, migration was added to remove duplicated records. Timezone change can only update date for 24 hours, so we are searching for records with start date around that range.
=> FIX: remove duplicated holidays because of timezone change

app/controllers/discourse_post_event/events_controller.rb, spec/requests/events_controller_spec.rb
Optional query param to support the detailed serializer that we replaced in https://github.com/discourse/discourse-calendar/pull/484
=> DEV: optional include_details param for events' list

app/controllers/discourse_post_event/events_controller.rb, assets/javascripts/discourse/adapters/discourse-post-event-event.js, assets/javascripts/discourse/components/upcoming-events-calendar.js, assets/javascripts/discourse/initializers/discourse-calendar.js, assets/javascripts/discourse/routes/discourse-post-event-upcoming-events-index.js, config/locales/server.en.yml, config/settings.yml, lib/discourse_post_event/event_finder.rb, spec/lib/discourse_post_event/event_finder_spec.rb, spec/requests/events_controller_spec.rb
Adds a new site setting to include expired events on calendar views (Upcoming Events and Category Calendar).
Past events are displayed with the configured color (from the category or from the "Map events to color" site setting) as text and border colors instead of the background.
=> FEATURE: site setting to include expired events on calendar views

assets/javascripts/discourse/components/upcoming-events-calendar.js, assets/javascripts/discourse/initializers/discourse-calendar.js
It should override the background color, unsetting it, to properly show an outline (color + border with equal colors).
=> UX: fix past events bg color

spec/integration/post_spec.rb, spec/integration/topic_spec.rb
In https://github.com/discourse/discourse/pull/24740, `min_trust_to_create_topic` site setting was replaced by `create_topic_allowed_groups`. This PR replaces the former, deprecated one, with the latter.
=> DEV: Replace deprecated min_trust_to_create_post

plugin.rb, spec/models/topic_query_spec.rb, spec/requests/sort_event_topics_spec.rb
**Context**
The discourse calendar plugin allows the creation of events. These events can be sorted by the `created_at` date when the `sort categories by event start date enabled` `SiteSetting` is enabled.
**Problem**
When the `sort categories by event start date enabled` `SiteSetting` is enabled the events are sorted from oldest to recent making it very difficult for the user to navigate and find Topics of interest
**Solution**
Fix how events are sorted so events that are closer to happening appear first and events that already happened appear from oldest to most recent
=> FIX: Event sorting shows oldest events first

assets/javascripts/discourse/adapters/discourse-post-event-event.js, assets/javascripts/discourse/initializers/discourse-calendar.js, test/javascripts/acceptance/category-events-calendar-outlet-test.js, test/javascripts/acceptance/category-events-calendar-test.js, test/javascripts/acceptance/upcoming-events-calendar-test.js
~~Uses the extension parameter of [`appendQueryParams`](https://github.com/discourse/discourse/blob/48193767bf753bedf9483b4a0c3b2f9760745df3/app/assets/javascripts/discourse/app/adapters/rest.js#L47) instead of appending it manually.~~
Removes all `.json` extension occurrences from all `/discourse-post-event/events` calls.
=> FIX: events endpoint extension

assets/javascripts/discourse/widgets/discourse-post-event.js
We know exactly which route this action exists on, so it's cleaner to lookup the route directly. (routeAction iterates through all active routes). Ideally this should be possible via a function on the composer service, but that would require a larger core change.
Ref https://github.com/discourse/discourse/pull/24946
=> DEV: Remove use of private routeAction function

app/controllers/discourse_post_event/events_controller.rb, assets/javascripts/discourse/components/upcoming-events-list.gjs, lib/discourse_post_event/event_finder.rb, spec/lib/discourse_post_event/event_finder_spec.rb, spec/requests/events_controller_spec.rb, test/javascripts/integration/components/upcoming-events-list-test.gjs
The upcoming events list component can be used via the [right sidebar blocks](https://github.com/discourse/discourse-right-sidebar-blocks) theme component.
It didn't have a limit previously, this PR changes it to assume a default of 8 entries and allows it to be tweaked via a `count` parameter just like other right sidebar blocks.
=> FEATURE: support count parameter on the events list component

assets/javascripts/discourse/components/upcoming-events-list.gjs, assets/stylesheets/common/upcoming-events-list.scss, config/locales/client.en.yml, test/javascripts/integration/components/upcoming-events-list-test.gjs
Adds a "View all" link from the upcoming events list to the `/upcoming-events` page.
=> UX: "view all" link on upcoming events list

plugin.rb, spec/serializers/post_serializer_spec.rb
We must include the year identifier since now we can use same topic to track holidays for multiple years. Also, we don't need to load old public holiday events for more than 6 months.
=> FIX: include year in holiday identifier to differentiate yearly recurring events.

assets/javascripts/discourse/components/upcoming-events-calendar.js, assets/stylesheets/common/upcoming-events-calendar.scss
Fixes https://meta.discourse.org/t/events-in-personal-messages-are-present-in-the-upcoming-events-page-but-not-visible/290950.
In addition to the fix, this PR changes the expired events to be displayed with 30% opacity (same as Google Calendar) instead of the previous outline approach.
=> FIX: expired events from PM not visible in upcoming events calendar

app/controllers/discourse_post_event/events_controller.rb, assets/javascripts/discourse/components/upcoming-events-list.gjs, lib/discourse_post_event/event_finder.rb, spec/lib/discourse_post_event/event_finder_spec.rb, spec/requests/events_controller_spec.rb, test/javascripts/integration/components/upcoming-events-list-test.gjs
Adds a `before` parameter to the events endpoint and uses it through a `upcomingDays` parameter to the upcoming events list component – which can be used when adding it to the right sidebar blocks theme component.
=> FEATURE: support upcomingDays parameter on the upcoming events list

spec/lib/discourse_post_event/event_finder_spec.rb
If `event1` and `event2` are fabricated in different second increments, this will flake.
Provide explicit timestamps to the fabricated events.
=> DEV: Fix time dependent flaky test

spec/requests/events_controller_spec.rb
Use explicit `starts_at` times for fabricated events to avoid flakiness
=> DEV: fix another time dependent flaky test

vendor/holidays/definitions/sg.yaml, vendor/holidays/lib/generated_definitions/sg.rb, vendor/holidays/test/defs/test_defs_sg.rb
https://www.mom.gov.sg/newsroom/press-releases/2023/0524-public-holidays-for-2024
=> DEV: Update public holiday for Singapore 2024

plugin.rb, spec/serializers/post_serializer_spec.rb
The `post_serializer_spec` was calling `Group.refresh_automatic_groups!(:admins)`, relying on that call booting system users from the group.
This change makes it so the implementation excludes any system users instead.
=> DEV: Exclude system users when serializing group timezones

spec/models/calendar_event_spec.rb, spec/serializers/post_serializer_spec.rb
We're changing how TL auto-groups are handled in core tests. These changes are needed to keep the `discourse-calendar` plugin tests passing.
=> DEV: Fix some TL group loading for admins in tests

vendor/holidays/definitions/us.yaml
No longer observed: https://www.nbcwashington.com/news/local/va-lawmakers-pass-bill-ending-lee-jackson-holiday/2223440
=> Remove Lee Jackson Day

spec/serializers/post_serializer_spec.rb
Looks like the change in bfd7f63 broke this test, this update should fix it
=> FIX: update test for holiday adjustments

assets/javascripts/discourse/widgets/discourse-post-event.js
"Add to calendar" will now prefill location with the url if present, and details with the associated post url, when using google calendar.
This has no tests as the feature is currently not tested at all in discourse-calendar and `downloadCalendar` is well tested in core.
Note: Im not adding a discourse compat entry as the current entry is already on the current discourse version.
=> FEATURE: use new options from downloadCalendar

assets/javascripts/discourse/components/upcoming-events-calendar.js, assets/javascripts/discourse/initializers/discourse-calendar.js
Category.findById should be used over site.categoryById map because that is an implementation detail that might be removed in the future.
=> DEV: Prefer Category.findById over categoryById

assets/javascripts/discourse/initializers/discourse-calendar.js
Same strategy from the `/upcoming-events` calendar:
https://github.com/discourse/discourse-calendar/blob/ad6feb27175a8af15e24d59808875637ff277593/assets/javascripts/discourse/components/upcoming-events-calendar.js#L134-L137
=> UX: use past event class name on the category calendar

vendor/holidays/definitions/gh.yaml, vendor/holidays/lib/generated_definitions/gh.rb, vendor/holidays/test/defs/test_defs_gh.rb
Switched to using a function for Eid-Ul-Fitr to make future updates seamless.
See https://www.mint.gov.gh/declaration-of-thursday-11th-april-2024-as-a-statutory-public-holiday/
=> DEV: Add upcoming Eid-Ul-Fitr holiday for Ghana

lib/discourse_calendar/site_settings/map_event_tag_colors_json_schema.rb
json_schema supports a color format, which is more user friendly... the format error message is unintelligible to most people:
It appears that we can just drop this in for free: 
`input type="color"` is supported by all the browsers we support
=> UX: use json_schema setting color format

assets/javascripts/discourse/components/event-date.gjs, assets/javascripts/discourse/connectors/topic-list-after-title/event-date.hbr, test/javascripts/acceptance/topic-title-decorator-test.js
Uses the start date when an event doesn't have an end date so that we always show the date in the topic title in topic lists.
Cf. https://meta.discourse.org/t/post-event-date-not-always-displayed-on-topic-title/258816
Inspired by https://github.com/discourse/discourse-calendar/pull/501
=> FIX: support endless events in topic list

app/models/discourse_post_event/event.rb, app/serializers/discourse_post_event/event_serializer.rb, assets/javascripts/discourse/lib/raw-event-helper.js, assets/javascripts/discourse/widgets/discourse-post-event-dates.js, assets/javascripts/discourse/widgets/discourse-post-event.js, assets/javascripts/discourse/widgets/more-dropdown.js, assets/stylesheets/common/discourse-post-event.scss, config/locales/client.en.yml, db/migrate/20240513140542_add_closed_to_discourse_post_event.rb, lib/discourse_post_event/event_parser.rb, spec/models/discourse_post_event/event_spec.rb, spec/system/post_event_spec.rb
Adds support for "closed" events instead of just relying on the start & end dates.
An event will be "expired" when it happened in the past.
An event might now also be "closed", if for whatever reasons, the author decides to "cancel" it.
Context - https://meta.discourse.org/t/when-closing-event-it-moves-it-to-todays-date-time/307292
=> FEATURE: closed events

assets/javascripts/discourse/initializers/discourse-calendar.js, assets/javascripts/discourse/lib/colors.js
…to increase contrast
Before / After
=> DEV: Tweak event text colors

assets/javascripts/discourse/lib/regions.js, config/locales/client.en.yml
Follow up to https://github.com/discourse/discourse-calendar/pull/568
Adding the required region.js addition for UAE `ae` by running `bin/rails javascript:update_constants` in Discourse root.
=> DEV: update regions js and missing uae translation

config/locales/server.en.yml
I am trying to enable `i18n.raise_on_missing_translations` in core. It caught a misplaced translation in this plugin. The key and the error message are there, but not nested in the right place.
**Before:**
```
Run options: include {:locations=>{"./plugins/discourse-calendar/spec/integration/post_spec.rb"=>[509]}}
Randomized with seed 20522
F
Failures:
1) Post with a private event when updating raw_invitees doesn’t accept usernames
Failure/Error:
expect { event_1.update_with_params!(raw_invitees: [lurker_1.username]) }.to raise_error(
ActiveRecord::RecordInvalid,
)
expected ActiveRecord::RecordInvalid, got #<I18n::MissingTranslationData: Translation missing: en.discourse_calendar.discourse_post_event.errors.models.event.raw_invitees.only_group> with backtrace:
Finished in 1.53 seconds …
```
=> FIX: Move misplaced error translation

assets/javascripts/discourse/connectors/topic-list-after-title/event-date.hbr, assets/stylesheets/common/discourse-post-event-core-ext.scss
=> UX: always wrap new dot and date onto same line

assets/stylesheets/common/discourse-post-event-core-ext.scss
This is a follow-up to https://github.com/discourse/discourse-calendar/pull/577 that also improves this on mobile, and adds a hack to hide an extra whitespace. 
/t/128649
=> UX: fix extra space and wrapping in topic lists

assets/javascripts/discourse/components/event-date.gjs, assets/javascripts/discourse/connectors/topic-list-after-title/event-date.hbr, assets/stylesheets/common/discourse-post-event-core-ext.scss
Follow-up to https://github.com/discourse/discourse-calendar/commit/9ef93a836b6a84d5341d3db24d798189ad609088
We can control the whitespace here now due to https://github.com/discourse/discourse/pull/27272/files
=> DEV: control whitespace, remove hack

assets/stylesheets/mobile/discourse-post-event.scss
- Ensure event status buttons don't overflow
- Ensure `show all` button does not wrap
=> UX: Update mobile event styling

vendor/holidays/definitions/gh.yaml, vendor/holidays/lib/generated_definitions/gh.rb, vendor/holidays/test/defs/test_defs_gh.rb
See https://www.mint.gov.gh/declaration-of-monday-17th-june-2024-as-a-public-holiday/
=> DEV: Add upcoming Eid-Ul-Adha holiday for Ghana

vendor/holidays/definitions/sa.yaml, vendor/holidays/lib/generated_definitions/sa.rb
The 15th of June to the 18th of June of 2024 is a public holiday in Saudi Arabia as per https://holidayapi.com/countries/sa/2024.
=> Add upcoming Saudi holidays (Eid Al Adha)

spec/integration/post_spec.rb
Requires https://github.com/discourse/discourse/pull/27173 to be merged.
Will add a `.discourse-compatibility` once merged.
=> FIX: BBCode parsing specs

assets/stylesheets/common/discourse-calendar.scss
Something about Safari really doesn't like that this grid is wrapped with flex, and it makes the rows very tall — using grid as the wrapper instead fixes this.
I also adjusted the calendar icons to be a little smaller to avoid causing horizontal overflow. 
Before:
After:
=> UX: fix group timezone layout in Safari

assets/javascripts/discourse/components/upcoming-events-calendar.js, assets/javascripts/discourse/initializers/discourse-calendar.js, assets/javascripts/discourse/lib/calendar-locale.js
Our old implementation was missing I18n for calendars in upcoming-events, this commit fixes it.
Related meta topic: https://meta.discourse.org/t/broken-no-i18n-in-calendar-plugin-upcoming-events-route/313745/2
before:
after:
=> UX: Add I18n translations for upcoming events

assets/javascripts/discourse/components/upcoming-events-list.gjs, test/javascripts/integration/components/upcoming-events-list-test.gjs
This is already the case for `monthFormat`. A blank `timeFormat` field results in a neater-looking list, if desired:
=> UX: Allow event time to be hidden if desired

assets/javascripts/discourse/initializers/discourse-calendar.js
This adds another priority: participant count, so events with multiple participants aren't buried under single-participant events in cases where there's a long list of multi-day events.
This is particularly useful for an employee leave/holiday calendar with automatic holidays enabled. Currently if there are many individuals with multi-day leave, this can bury a holiday even if it has many more participants. 
Before (multi-day events above multi-participant events):
After (multi-participant events get priority, then multi-day events):
=> UX: prioritize events with high participant counts

assets/javascripts/discourse/components/modal/post-event-builder.js
Replaces hardcoded strings on the event builder modal by existing i18n strings.
=> UX: fix event builder i18n

assets/javascripts/discourse/initializers/discourse-calendar.js, spec/system/category_calendar_spec.rb
The previous URL parsing code was not resilient to these paths, we now use the router to recognize these paths and extract the params we need.
=> FIX: shows category calendar on hot/latest

assets/javascripts/discourse/components/upcoming-events-calendar.js, assets/javascripts/discourse/initializers/discourse-calendar.js, assets/javascripts/discourse/lib/add-recurrent-events.js, test/javascripts/acceptance/category-events-calendar-test.js
Bringing parity to the same behavior from the `/upcoming-events` calendar.
=> UX: add upcoming events from recurrence to the category calendar

assets/javascripts/discourse/components/discourse-post-event/index.gjs
This decorator will be used to add new info in the status. It also gives the `<Separator />` component as outletArgs to simplify usage.
=> DEV: adds a post event status decorator

assets/javascripts/discourse/components/discourse-post-event/index.gjs
This was not stopping the behavior (very lucky) but it was causing errors on destroy as the teardown function doesn't exist.
We don't have yet tests to ensure message bus is working between session, it's a little bit involved I will wait few more refactors and consensus on new design.
=> DEV: correctly setup modifier

assets/javascripts/discourse/components/discourse-post-event/creator.gjs, assets/javascripts/discourse/components/discourse-post-event/dates.gjs, assets/javascripts/discourse/components/discourse-post-event/event-status.gjs, assets/javascripts/discourse/components/discourse-post-event/index.gjs, assets/javascripts/discourse/components/discourse-post-event/invitees.gjs, assets/javascripts/discourse/components/discourse-post-event/more-menu.gjs, assets/javascripts/discourse/components/discourse-post-event/status.gjs, assets/javascripts/discourse/components/discourse-post-event/url.gjs, assets/stylesheets/common/discourse-post-event.scss, config/locales/client.en.yml, config/locales/server.en.yml, config/settings.yml
Interested and not going are generally not used.
To avoid adding this clutter to the UI we now suppress this.
Sites wishing to have these buttons can amend the `event_participation_buttons` site setting
Also:
- Add a show participants button even if there are no participants (so admins can populate events)
- Fix localization for event participation
- Allow toggling attendance by pressing the same button
- Removes leave event button from the dropdown menu
- Refactors outlets to allow maximum flexibility
=> FEATURE: suppress interested and not going buttons by default

assets/javascripts/discourse/components/discourse-post-event/index.gjs, spec/system/post_event_spec.rb
This has been lost during the move to glimmer.
=> FIX: correctly render html of event title

assets/javascripts/discourse/initializers/discourse-post-event-decorator.gjs
This could happen during a server error for example. Ideally we should ensure the post event doesn't disappear on such error, but at least for now we avoid the crash.
=> FIX: prevents error if post event node is not found

assets/javascripts/discourse/components/discourse-post-event/more-menu.gjs
The previous one has been removed in https://github.com/discourse/discourse-calendar/commit/d31933bf4963ad8c107e9a9c0e8349a2b96145ad
=> FIX: correctly set upcoming events key

app/models/discourse_post_event/invitee.rb, assets/javascripts/discourse/models/discourse-post-event-event.js, assets/javascripts/discourse/models/discourse-post-event-invitees.js, assets/javascripts/discourse/services/discourse-post-event-api.js
This commit has 3 parts:
- Ensuring than when attempting to join a event we return an invitee even if the user was already part of the event, before we would return null which would have required a special handling. In this case we were just adding a null invitee.
- Ensures invitees/suggestedUsers/sampleInvitees use tracked properties correctly. And do not require to manually create a TrackedArray, the model should always handle this implementation detail.
- When joining an event we were pushing the watchingInvitee to the sampleInvitees even when the watchingInvitee was null, which would create an error.
=> FIX: prevents pushing null watching invitee

assets/javascripts/discourse/adapters/connectors/category-custom-settings/show-event-category-sorting-settings.hbs
Following the key change in https://github.com/discourse/discourse-calendar/commit/d31933bf4963ad8c107e9a9c0e8349a2b96145ad this has been broken.
This commit also hides the section if `sort_categories_by_event_start_date_enabled` AND `disable_resorting_on_categories_enabled` are not enabled, prior to this change we would just show the title, with no checkbox to check.
=> FIX: category settings for calendar were incorrect

app/models/discourse_post_event/event.rb, app/models/discourse_post_event/event_date.rb, spec/integration/post_spec.rb
Prior to this fix when computing the next event date we were resetting the status of every invitees. The status will now only be reset for non going users.
=> FEATURE: keeps going invitees for recurring events

db/migrate/20200409102639_drop_incorrect_future_schema_migrations.rb, db/migrate/20200409120815_rename_topic_custom_field_topic_post_event_starts_at_index.rb, db/migrate/20200409181607_remove_display_invitees.rb, db/migrate/20200926144256_add_unique_index_to_topic_event_ends_at_custom_field.rb, db/migrate/20220724130519_fix_post_event_timezones.rb
We are adding the Rails/ReversibleMigrationMethodDefinition cop to rubocop-discourse, this change resolves existing errors under this rule.
=> DEV: resolve Rails/ReversibleMigrationMethodDefinition errors

assets/javascripts/discourse/components/upcoming-events-list.gjs, test/javascripts/integration/components/upcoming-events-list-test.gjs
(This PR refers to the [interactivity](https://meta.discourse.org/t/discourse-calendar-and-event/97376#p-473517-integrations-with-other-plugins-7) between the discourse-calendar plugin and the right-sidebar-blocks component.)
As of now, only the first day of an event gets listed in the Upcoming Events sidebar. So if the event is from `10-22-2024 to 10-26-2024,` only the 22nd would have the event on it. On the 23rd, you wouldn't know the event was still happening.
Before:
(Note that this screenshot was taken on October 28th, and the event's start date shows up)
After:
(Taken on the same day, so only the remaining event days show up)
I tested this with both single-day events and multi-day events. We might need to add a limit on the number of results we get back. (If someone throws in a …
=> DEV: Adds ability to see multiday events in sidebar

assets/javascripts/discourse/helpers/format-event-name.js, assets/javascripts/discourse/helpers/format-future-date.js
(`format-event-name` was unused)
=> DEV: Convert helpers to plain functions

assets/javascripts/discourse/components/upcoming-events-list.gjs, config/locales/client.en.yml, config/locales/server.en.yml, config/settings.yml, lib/discourse_calendar/site_settings/map_events_title_json_schema.rb, test/javascripts/integration/components/upcoming-events-list-test.gjs
This allows users to change the title of the calendar sidebar according to the category. The example use-case is "Upcoming Releases" in the "Product News" category.
Default:
Custom:
Setting:
Tests will be added into the Right Sidebar Blocks component, as this feature only works in conjunction with specific settings in that component.
=> FEATURE: Allow users to set a custom title to sidebar calendar

.discourse-compatibility, plugin.rb
This PR updates deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
=> DEV: Update deprecated Font Awesome icon names

assets/javascripts/discourse/components/discourse-post-event/invitees.gjs, assets/stylesheets/common/discourse-post-event.scss
This PR adds a "going" count back into the events UI. The counts were removed previously to minimize the amount of information, but "going" should have remained.
**After**
**Before**
=> UX: Render invitees count

assets/javascripts/discourse/components/discourse-post-event/more-menu.gjs, assets/javascripts/discourse/components/discourse-post-event/status.gjs, assets/javascripts/discourse/components/modal/post-event-builder.hbs, assets/javascripts/discourse/components/modal/post-event-bulk-invite.hbs, assets/javascripts/discourse/components/modal/post-event-invitees/index.gjs
This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
=> DEV: Update more deprecated Font Awesome icon names

spec/system/disable_sort_spec.rb
Otherwise it'll fail if some other incompatible plugin is installed at the same time
=> DEV: Force enable glimmer topic list in specs

assets/javascripts/discourse/components/discourse-post-event/dates.gjs
The next ensures `this.htmlDates` has correctly been set and a render is on going which is going to be awaited by the schedule render. Before this fix `querySelectorAll` could return an empty nodes list as the dates were not rendered yet.
=> FIX: correctly apply local dates on event dates

assets/javascripts/discourse/components/discourse-post-event/invitees.gjs, assets/stylesheets/common/discourse-post-event.scss
This PR removes the "0 Going" indicator if an event is standalone. Because users cannot mark they are "going" to a standalone event, the "0 Going" was always present, which is not ideal.
I also added a small line of CSS to always add padding to the bottom of the last section equal to the to section in the event post component.
**Before**
**After**
=> UX: Remove going indicator for standalone events

vendor/holidays/definitions/sg.yaml, vendor/holidays/lib/generated_definitions/sg.rb
Dates are referenced from https://www.mom.gov.sg/newsroom/press-releases/2024/0805-public-holidays-for-2025
=> DEV: Update Public Holidays for Singapore 2025

assets/javascripts/discourse/components/upcoming-events-calendar.js
=> FIX: row height on the upcoming events calendar

assets/javascripts/discourse/components/discourse-post-event/index.gjs, assets/javascripts/discourse/components/discourse-post-event/more-menu.gjs, spec/system/post_event_spec.rb
This PR adds logic in order to *not* show the "show participants" button in the `more` dropdown on standalone events.
**After**
**Before**
=> UX: Do not show participants in admin drop down menu for standalone events

assets/javascripts/discourse/components/discourse-post-event/invitee.gjs, assets/javascripts/discourse/widgets/discourse-group-timezones-reset.js
This PR updates the deprecated `times` and `undo` icon names, and removes some `fa-` prefixes which we remove in core anyway. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
=> DEV: update more deprecated icon names

assets/javascripts/discourse/components/discourse-post-event/dates.gjs
As per CvX:
> schedule("afterRender") inside next() is extraneous - next already schedules a separate run loop, so specifying that this code needs to run in the "afterRender" part of it shouldn't change anything
=> DEV: schedule is un-necessary

lib/holiday_status.rb, spec/models/calendar_event_spec.rb
`DiscourseCalendar::CreateHolidayEvents` periodically deletes holiday events to recreate updated ones. If one of the events belonged to a user that has been destroyed and if `enable_user_status` was enabled, the `after_destroy` hook would raise an exception.
=> FIX: Allow events belonging to deleted users to be destroyed

assets/javascripts/discourse/components/discourse-post-event/more-menu.gjs, spec/system/post_event_spec.rb
=> FIX: do not show 'send pm' button to the user who created the event

assets/javascripts/discourse/components/discourse-post-event/more-menu.gjs, assets/javascripts/discourse/pre-initializers/transformers.js, test/javascripts/integration/components/more-menu-test.gjs
Plugins can add a value transformer to show participants in the event more menu. This is useful for plugins that want to show participants in the event more menu, but the user currently does not have the authority to see the participants, this gives more flexibility to do so.
=> FEATURE: Add value transformer for showing participants in the event more menu

assets/stylesheets/common/discourse-post-event.scss
This PR uses the correct border-radius variable.
=> UX: Use correct border radius variable

assets/javascripts/discourse/components/upcoming-events-calendar.js, assets/javascripts/discourse/initializers/discourse-calendar.js, test/javascripts/acceptance/category-events-calendar-test.js
There are three places in this plugin where FullCalendar is set up.
In one of these three the parameter firstDay: 1 is passed, in the other two it's not. This leads to an inconsistency where the Upcoming Events calendar begins on Sunday, whereas the topic calendars start on Monday. (See https://meta.discourse.org/t/choose-first-day-of-the-week-on-upcoming-events-calendar/307785/5)
Ideally this would be taken from the users (browser) preferences, but since [all other places in core](https://github.com/search?q=repo%3Adiscourse%2Fdiscourse%20firstDay&type=code) hard code it to firstDay: 1 as well, this small patch at least adds some consistency.
=> Fix for inconsistent first-day-of-the-week display.

assets/stylesheets/colors.scss
Fails with `"Error: @use rules must be written before any other rules"` because color stylesheets are concatenated
Followup to fc3f4071ff8bbe25eb05cd9440cc39f1442a5072
=> FIX: Revert colors.scss changes

assets/stylesheets/common/discourse-calendar.scss
When a calendar has enough entries that it needs to scroll within its container, it can't quite scroll far enough, causing the last row to be slightly cut off.
This fix tweaks the size of the scroll container to ensure the last row is fully visible.
Test that the calendar scrolls fully on different browsers and devices.
Note that there is still some cut-off on particularly small resolutions (<500px wide) due to the way the Month/Week/List buttons are shifted around.
=> FIX: Decrease height of the calendar scroller.

spec/system/category_calendar_spec.rb
Playwright will not accept this kind of specs as it's not reliable. You would potentially get this error:
```
Playwright::Error:
Element is not attached to the DOM
Call log:
- attempting click action
-     - waiting for element to be visible, enabled and stable
```
What happens is that the ".nav-item_latest" would be present before navigation, and playwright would find it just before the page has loaded, the click though might happen right after page transition and the initial element wouldn't be attached to the dom anymore.
=> DEV: ensures we are on correct page

spec/system/post_event_spec.rb
This won't work in the future for playwright.
=> DEV: fill in doesnt trigger key down/up/press events

plugin.rb, spec/models/discourse_post_event/user_spec.rb
When `discourse_post_event_allowed_on_groups` is set to `everyone`, everyone should be able to create post events.
https://meta.discourse.org/t/selecting-the-everyone-group-in-the-allowed-on-groups-setting-does-not-enable-event-creation/279434
=> FIX: allow create events for everyone group

app/serializers/discourse_post_event/event_summary_serializer.rb, assets/javascripts/discourse/lib/add-recurrent-events.js, lib/discourse_post_event/rrule_generator.rb, spec/integration/recurrence_spec.rb, spec/lib/discourse_post_event/rrule_generator_spec.rb, spec/serializers/discourse_post_event/event_summary_serializer_spec.rb, spec/system/upcoming_events_spec.rb, test/javascripts/acceptance/category-events-calendar-test.js, test/javascripts/acceptance/upcoming-events-calendar-test.js
- we were not applying the timezone for the list of upcoming events
- we would return the first event + the upcoming events, we now get all the events generate by RRule if this is a recurring event, and if it's not a recurring event we just return the event, instead of doing a dance where we would remove the first event from RRule but prepend the initial event on the frontend
=> FIX: prevents double event and uses correct starts_at

assets/javascripts/discourse/components/group-timezones/index.gjs
Since it was converted to Glimmer, the nbsp html entity is being escaped by ember before rendering. We can use a unicode literal instead.
Followup to d471bbdf9aab7579e99ddf73c9f0d4343764fc2e
=> FIX: nbsp handling in group-timezones

assets/javascripts/discourse/components/discourse-post-event/dates.gjs, test/javascripts/integration/components/dates-test.gjs
This PR overhauls the way event dates are rendered by applying context-aware formatting rules:
* Single-day events only show times when appropriate, hiding “12:00 AM” for events without `endDate`.
* Multi-day ranges omit redundant parts (e.g. for the current year) and include weekday/month/day when needed.
* Weekday-only ranges (e.g. “Friday → Monday”)
* Same-week and same-month spans (omitting year)
* Cross-month and cross-year spans (including year where needed)
* `Today/Yesterday/Tomorrow` labels with time ranges
* Same-day events showing only time  ￼
* Improves readability of event dates across the app
* Reduces visual noise by hiding redundant date/time fragments
* Ensures consistency with user expectations around relative dates
* Relative labels (`Yesterday, Today, Tomorrow`) …
=> UX: smart format dates

assets/javascripts/discourse/components/discourse-post-event/dates.gjs
This will produce a string wrapped in standard ASCII double quotes (") and prevent the browser from substituting them with language-specific typographic quotes, such as the German „ (low-9) and “ (left double).
=> FIX: uses Unicode escape sequence for a standard double quote

assets/javascripts/discourse/components/discourse-post-event/dates.gjs
Two changes introduced:
- DRY date formatting for start/end datetimes.
- Escape double quotes for German locale.
Fixes the issue raised in Meta: https://meta.discourse.org/t/calendar-event-seems-broken/371517/10.
=> FIX: escapes localization for double quotes

assets/javascripts/discourse/components/upcoming-events-calendar.gjs
This is a recent regression due to https://github.com/discourse/discourse-calendar/commit/bdf8869a0186264148ad95a2659fd863400db9e3
I wanted to write a test, but this is non trivial given this is a standalone component. We also have other internal repos testing this behavior (how I discovered the regression). Will try to have  a test for this one later.
=> FIX: ensures UpcomingEventsCalendar can be used alone

app/serializers/discourse_post_event/event_summary_serializer.rb, assets/javascripts/discourse/components/upcoming-events-calendar.gjs, assets/javascripts/discourse/helpers/format-event-name.js, assets/javascripts/discourse/initializers/discourse-calendar.js, config/locales/client.en.yml, spec/system/page_objects/discourse_calendar/upcoming_events.rb, spec/system/upcoming_events_spec.rb
When an event is set with `show_local_time=true` we will display the local time of the event in the calendar.
Eg: My Event (Local time: 8:10am)
Note that if a user is in the same timezone than the event, we won't show the local time text.
=> UX: displays event local time in calendar

test/javascripts/acceptance/upcoming-events-calendar-test.js
The commit https://github.com/discourse/discourse-calendar/commit/d878317c5f875fc7e67c0acbae62b7a6fb0849a7 set the calendar timezone to the user’s timezone when available and as result broke this test.
=> FIX: broken test due to user timezone 
